#source 'https://Rocfly@bitbucket.org/Rocfly/lxgpsmanagespecs.git'

platform:ios, '8.0'


target 'RocUsually' do
    
    #pod 'UtilityOC',:Git=>"https://Rocfly@bitbucket.org/Rocfly/rputilityocspecs.git"

#pod 'MyLib', '~> 0.1.0'

#pod 'LXGpsManager', :git => 'https://Rocfly@bitbucket.org/Rocfly/lxgpsmanage.git', :tag => '0.1.4'

#    pod 'LXGpsManager', '~> 0.1.2'
    pod 'WXDevtool', '~> 0.9.5', :configurations => ['Debug']
    pod 'RDVTabBarController', '~> 1.1.9'
	pod 'AFNetworking', '~> 3.0.0'
	pod 'Masonry', '~> 0.6.1'
	pod 'SDWebImage', '~>3.6'
	pod 'FrameAccessor'
	pod 'DACircularProgress' ,'~> 2.3.1'
	pod 'MJRefresh'
	pod 'MJExtension', '~> 3.0.8'
	pod 'MBProgressHUD', '~> 0.9.1'
	pod 'IQKeyboardManager', '~> 3.3.4'
    pod 'CYLTableViewPlaceHolder'
    pod 'KINWebBrowser', '~> 1.3.2'
    pod 'Baidu-Maps-iOS-SDK', '~> 3.0.0'
    pod 'WeexSDK', :path=>'./sdk/'
    pod 'PNChart', '~> 0.8.9'
    
    pod 'ReactiveObjC', '~> 2.1.2'


#    pod 'BaiduMapKit', '~> 3.2.1'
#pod 'ReactiveCocoa', '~> 5.0.0'

#  pod 'CTMediator', '~> 0.0.3'#casa  组件化 框架


end

target 'RocUsuallyTests' do
    pod 'RDVTabBarController', '~> 1.1.9'
    pod 'AFNetworking', '~> 3.0.0'
    pod 'Masonry', '~> 0.6.1'
    pod 'SDWebImage', '~>3.6'
    pod 'FrameAccessor'
    pod 'DACircularProgress' ,'~> 2.3.1'
    pod 'MJRefresh'
    pod 'MJExtension', '~> 3.0.8'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'IQKeyboardManager', '~> 3.3.4'
    pod 'CYLTableViewPlaceHolder'
    pod 'STAlertView', '~> 1.0.0'
#	source 'https://Rocfly@bitbucket.org/Rocfly/rputilityocspecs.git' 
#	pod 'UtilityOC', '~> 0.1.0'

end

